name = "PolarizedTypes"
uuid = "d3c5d4cd-a8ee-40d6-aac7-e34df5a20044"
authors = ["Paul Tiede <ptiede91@gmail.com> and contributors"]
version = "0.1.3"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"

[extensions]
ChainRulesCoreExt = "ChainRulesCore"

[compat]
ChainRulesCore = "1"
DocStringExtensions = "0.9"
PrecompileTools = "1"
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
